apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: test-pattern-operator
  namespace: openshift-marketplace
spec:
  displayName: Test Pattern Operator
  sourceType: grpc
  image: CATALOG_IMG
